### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by ghost** [ShqWW/copymanga-download#1]
请问可不可以添加一下国内可以直连的拷贝网址，挂梯子下载时间长了一直很慢切换梯子节点效果也不是太好，还有就是下载默认地址设置是否可以出个记忆功能，可以省的次次打开之后修改下载地址，谢谢了。

**Comment by ShqWW** [comment]
1. 设置里有不同的域名选项，可以多尝试几个
2. 记忆功能有时间以后更新

**Comment by ghost** [comment]
好的谢谢
