### ISSUE TITLE
章节无法下载

### ISSUE THREAD

**Issue by startsky12138** [ShqWW/copymanga-download#2]
![48EE4BB1-F399-4D2C-BA8A-01A4F45D9B99](https://github.com/ShqWW/copymanga-download/assets/167861488/973274d5-da01-41d2-bcb5-74603bd5aed3)
![46E1EDD3-AC19-46AE-9051-3F172D1A5D1E](https://github.com/ShqWW/copymanga-download/assets/167861488/8d86ff9b-5a30-4e34-937f-f9b39bcd6009)

**Comment by ShqWW** [comment]
已修复
